language: go

language: go

go:
- 1.x
- tip

matrix:
  fast_finish: true
  allow_failures:
  - go: tip

before_install:
- sudo apt-get install -y libsystemd-journal-dev
- go get -u github.com/golang/dep/cmd/dep
- go get -u github.com/alecthomas/gometalinter
- gometalinter --install

script:
  - dep check
  - gometalinter ./... --config .gometalinter.json
  - go test -coverprofile=coverage.txt -covermode=atomic ./...

after_success:
- bash <(curl -s https://codecov.io/bash)

addons:
  apt:
    update: true
