language: go
dist: xenial

go:
- 1.13
- tip

env:
- GO111MODULE=on

matrix:
  fast_finish: true
  allow_failures:
  - go: tip

before_install:
- sudo apt-get install -y libsystemd-dev
- curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | sh -s -- -b $(go env GOPATH)/bin v1.21.0

script:
  - golangci-lint run
  - go test -mod=vendor -coverprofile=coverage.txt -covermode=atomic ./...

after_success:
- bash <(curl -s https://codecov.io/bash)

addons:
  apt:
    update: true
