language: go
dist: xenial

matrix:
  include:
    - os: linux
      env: LINUX=true
      cache:
        directories:
          - $HOME/.cache/go-build
          - $HOME/gopath/pkg/mod

    - os: osx
      cache:
        directories:
          - $HOME/Library/Caches/go-build
          - $HOME/gopath/pkg/mod

go:
- 1.15
- tip

env:
- GO111MODULE=on

before_install:
- if $LINUX; then sudo apt-get install -y libsystemd-dev;
- curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | sh -s -- -b $(go env GOPATH)/bin v1.21.0

script:
  - golangci-lint run
  - go test -mod=vendor -coverprofile=coverage.txt -covermode=atomic ./...

after_success:
- bash <(curl -s https://codecov.io/bash)

addons:
  apt:
    update: true
