FORMAT: 1A
HOST: http://master.dcos.io:1050/system/health/v1

# dcos-diagnostics 

## Diagnostics Bundles [/system/health/v1]

### List All Bundles [GET /report/diagnostics]

Get list of all bundles and their state

+ Response 200 (application/json)

        [
            {
                "id": "123e4567-e89b-12d3-a456-426655440000",
                "started_at": "2015-08-05T08:40:51.620Z",
                "stoped_at": "2015-08-05T08:40:51.620Z",
                "size": 64,
                "status": "DONE"
            }
        ]

### Create a New Bundle [PUT /report/diagnostics/{id}]

The `LOCAL` bundle can be created at any node when dcos-diagnostics is running.
The special case is when user specify `REMOTE` type.
This works only on masters and means the budnle will be creaded on selected nodes.

+ Parameters
    + id - an identifier of a new bundle

+ Request (application/json)

        {
            "type": "REMOTE",
            "nodes": ["node1", "node2", "node3"]
        }

+ Response 202 (application/json)

    The bundle is accepted. This means master nodes is sending requests to remote nodes asking them for a bundle.

    + Body

            {
                "id": "123e4567-e89b-12d3-a456-426655440001",
                "started_at": "2015-08-05T08:40:51.620Z",
                "size": 0,
                "status": "STARTED"
            }


+ Response 409 (application/json)

    Another bundle with same {id} was already started

    + Body

            {
                "code": 409,
                "error": "bundle 123e4567-e89b-12d3-a456-426655440001 already exists"
            }

+ Response 507 (application/json)

    There is a problem with storage

    + Body

            {
                "code": 507,
                "error": "could not create bundle 123e4567-e89b-12d3-a456-426655440001 workdir"
            }

### Delete a Bundle [DELETE /report/diagnostics/{id}]

When bundle exists and is `DONE` it delete the bundle file.
If bundle was already `DELETED` is does not change it state.

+ Parameters
    + id - an identifier of a new bundle

+ Response 200 (application/json)

    + Body

            {
                "id": "123e4567-e89b-12d3-a456-426655440001",
                "started_at": "2015-08-05T08:40:51.620Z",
                "stoped_at": "2015-08-05T08:40:51.620Z",
                "size": 0,
                "status": "DELETED"
            }

+ Response 404 (application/json)

    Bundle with given id never existed

    + Body

            404 page not found

+ Response 500 (application/json)

    Bundle could not be read

    + Body

            {
            "id":"bundle-state-not-json",
            "status":"Unknown",
            "started_at":"0001-01-01T00:00:00Z",
            "stopped_at":"0001-01-01T00:00:00Z",
            "errors":[
                "could not unmarshal state file bundle-state-not-json: invalid character 'i' looking for beginning of value"
            ]
            }

### Cancel a Bundle (NOT IMPLEMENTED) [DELETE /report/diagnostics/{id}]

This method is not implemented, see: [DCOS_OSS-5222](https://jira.mesosphere.com/browse/DCOS_OSS-5222)

When bundle is in progress (`STARTED`, `PROCESSING`) it cancel bundle creation and remove all intermidiete files.
If bundle was already `CANCELED` is does not change it state.

+ Response 200 (application/json)

    + Body

                {
                "id": "123e4567-e89b-12d3-a456-426655440001",
                "started_at": "2015-08-05T08:40:51.620Z",
                "stoped_at": "2015-08-05T08:40:51.620Z",
                "size": 0,
                "status": "CANCELED"
                }

+ Response 404 (application/json)

    Bundle with given id never existed

    + Body

            404 page not found

### Get a Bundle status [GET /report/diagnostics/{id}]

Get status of a signle bundle `id`

+ Parameters
    + id - an identifier of a new bundle

+ Response 200 (application/json)

    + Body

            {
               "id": "123e4567-e89b-12d3-a456-426655440001",
               "size":494,
               "status":"Deleted",
               "started_at":"2015-08-05T09:40:51.62Z",
               "stopped_at":"2015-08-05T10:40:51.62Z",
               "errors":[
                  "could not collect collector-1: some error"
               ]
            }

+ Response 404 (application/json)

    + Body

            404 page not found

+ Response 500 (application/json)

    Bundle could not be read

    + Body

            {
            "id":"bundle-state-not-json",
            "status":"Unknown",
            "started_at":"0001-01-01T00:00:00Z",
            "stopped_at":"0001-01-01T00:00:00Z",
            "errors":[
                "could not unmarshal state file bundle-state-not-json: invalid character 'i' looking for beginning of value"
            ]
            }

### Get a Bundle file [GET /report/diagnostics/{id}/file]

Get content of a bundle with given `id`

+ Parameters
    + id - an identifier of a new bundle

+ Response 200 (application/zip)


    + Headers

            Last-Modified: Tue, 28 May 2019 15:43:40 GMT

+ Response 410 (application/json)

    Bundle was deleted, canceled or failed. There is no bundle file.

    + Body

            {
            "code":410,
            "error":"bundle bundle-0 was Deleted"
            }

+ Response 404 (application/json)

    Bundle is not done yet.

    + Body

            {
            "code":404,
            "error": "bundle 123e4567-e89b-12d3-a456-426655440001 is not done yet (status Started), try again later"
            }

+ Response 500 (application/json)

    Bundle could not be read

    + Body

            {
            "id":"bundle-state-not-json",
            "status":"Unknown",
            "started_at":"0001-01-01T00:00:00Z",
            "stopped_at":"0001-01-01T00:00:00Z",
            "errors":[
                "could not unmarshal state file bundle-state-not-json: invalid character 'i' looking for beginning of value"
            ]
            }